# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='date launched')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
