# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0)),
                ('diameter', models.FloatField(default=0)),
                ('mass', models.IntegerField(default=0)),
                ('stages', models.IntegerField(default=0)),
                ('payload_to_leo', models.IntegerField(default=0)),
                ('payload_to_gto', models.IntegerField(default=0)),
                ('payload_to_mars', models.IntegerField(default=0)),
            ],
        ),
    ]
