# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='Falcon 9', max_length=100),
            preserve_default=False,
        ),
    ]
